### ISSUE TITLE
ROS2 Version?

### ISSUE THREAD

**Issue by mechwiz** [swri-robotics/message_serialization#8]
Out of curiosity, are there plans to make a ros2 version of this package?

**Comment by marip8** [comment]
I haven't thought too much about porting this package to ros2. There are some limitations to the approach taken here, primarily supporting backwards compatibility with message definitions, that might make me want to choose some differential serialization approach (maybe  `boost_serialization` with a [YAML archive](https://github.com/rwols/yaml-archive)) instead of directly porting. I've used this repo a lot in the past for custom messages, and it's painful to convert files after changing the definition of a message. If this is something you're interested in, I can help lay out a roadmap for updating this repo for compatibility with ROS2

**Comment by mechwiz** [comment]
Thanks for offering! I'm not sure I need this just yet but wanted to explore my options. I used this package for some ROS1 applications involving serializng and deserializing trajectory messages and found it very helpful :)
